apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-data-prep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mage-data-prep
          image: mageai/mageai:latest
          ports:
            - containerPort: 6789
          volumeMounts:
          - name: efs
            mountPath: "/home/src"
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs-storage-claim
